language: node_js
node_js: "node"
services:
  - mongodb
deploy:
  provider: heroku
  secure: "Na3P0frNf+2lHz3hLE3w21xZG5KydLXHT3XpFqEMtTVKfhTL0FrSwXnS8+7DdSMVW3lZxSjmKW1nyxHseTbVMOBAmrPSVKIEJ+tWw0kc3qZpHXrpAt3/V/QnmTlYUV5rYcZysfjaYs+MsdpS0gZlQ1y14qdTRI1TZoyvv6bQdsQeVAGWUVl6VvI3a1Vg15cScu0c89Y45BGP917nf4CouGgtNP/oa+zG5aa83vkC2KR3FkyZHAZncXEkBfmOSEyqUTx6T1mjrYOLtH8BGniEzKGwNrd/T7Q8TGe/GTMejRwdXRzGoclknv4DW7nDbCayLgUtRPSAwqTtBMouz2197jFjc5X6TsJMxBPT5X+tqjjt2z00M6E3xNt08Eaq2ErBaRHK3vWH7svHnr5Qt3qbkYni0QVlrbaYX4VwpLnXxfhFu8ZE7E3TQ1sxCNexGKKUNZeBi+U4fzrFSC7Q2SEZ6QFMVw/w4ReVozu2r0zC4UATF/GEErMXn9f8B8mL8K10uNItp/1Lg1I3XiAM2nQCktLPPUPi9ih0TNmW0B0OinqU+Ap30kvkJfS/X+5GcRIKzdQVwZdEiOoZfmQH7xEWHOs/zIWG0HOj4dRRKybq8VN8Rqv6BGLYn7kPQCqh5f4r8wlDFXtVnbEVdWNO7+1tbALy3+qkZBADYU6gUt0cnXA="
env: MONGODB_URI=mongodb://127.0.0.1:27017/mineralsapi
